### ISSUE TITLE
Delete single label

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#119]
# Idea
## User story
As as user, I want to be able to just delete one or two labels, instead of all of them.

## Technical requirements
- [x] Change the button from *Remove all labels* to *Remove labels*
- [x] Only remove the labels that have been selected
- [x] Gray out the button if no labels are selected

## Frontend implementation
[Aragon PR](https://github.com/aragon/aragon/pull/829)
[aragon.js PR](https://github.com/aragon/aragon.js/pull/324)
