### ISSUE TITLE
DAO templates refactor

### ISSUE THREAD

**Issue by facuspagnuolo** [aragonone/product#127]
# Idea
## User story
Make DAO templates more reusable without having to repeat to much code and requiring too much knowledge of how DAOs are implemented under the hood allow new users to onboard easily.

## Implementation
- [x] Minimum viable refactor to allow creating templates more easily - [PR #93](https://github.com/aragon/dao-kits/pull/93) (sprint 21)
- [x] Improve multisig template tests - [PR #94](https://github.com/aragon/dao-kits/pull/94) (sprint 22)
- [x] Improve democracy template tests - [PR #95](https://github.com/aragon/dao-kits/pull/95) (sprint 22)
- [x] Write bare template tests - [PR #96](https://github.com/aragon/dao-kits/pull/96) (sprint 22)
- [x] Review (sprint 22)
