### ISSUE TITLE
0.8 polish

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#133]
Master list of items to fix/polish for 0.8.

# Completed

## Client

- [x] Once HelpScout has been enabled, [trying to disable it in Preferences does nothing](https://user-images.githubusercontent.com/4166642/61958044-e01ba300-afc0-11e9-8fe2-fd324cfd491a.png) (just seems to remove the beacon CSS) ([PR](https://github.com/aragon/aragon/pull/905))
- [x] HelpScout new designs ([PR](https://github.com/aragon/aragon/pull/905) - includes changes in color, pending specs)
- [x] Organization Switcher's [dropdown appears on top of the org name](https://user-images.githubusercontent.com/4166642/61959409-a13b1c80-afc3-11e9-80b5-006af8fb02b8.png)
- [x] Update DropDown api
- [x] Update with new `Field`
- [x] Native SidePanel overlay (only over app view?)
- [x] Update with new `Link`
- [x] Update `AutoComplete`, `LocalIdentitiesAutoComplete`
- [x] Remove `color`, `font`, and `theme` imports from aragonUI
- [x] Update large images (@owisixseven) [Folder with the optimized img](https://www.dropbox.com/sh/asl0vv3h8pg33e4/AAAtctA4HBd8U56Olf47NtjLa?dl=0)
- [x] [Redesign 404 screen](https://github.com/aragon/aragon/pull/939#issue-312439433) (@owisixseven) - Designs [here](https://www.figma.com/file/YfLiVQwfqUUdOnCxS1HtPS/Untitled?node-id=0%3A1)
- [x] Update with `AddressBadge`'s `labelStyle`, `label`
- [x] Final design reviews (Sprint 29)
  - [x] Activity panel
  - [x] App center
  - [x] DropDown headers and placeholders ([ref Figma file](https://www.figma.com/file/XW5MImCLiXn3OW1RYH9L5e/Dropdowns-headers-and-placeholders?node-id=0%3A1))
- [x] Safari:
  - [x] Organization view is only rendered for ~50px from the top
  - [x] Not loading app frontends
- [x] Update screenshots for Voting, Finance, Tokens
- [x] Test signer panel with Frame (see https://github.com/aragonone/product/issues/133#issuecomment-528622692)

## Onboarding

- [x] [Notion list](https://www.notion.so/aragon/Design-review-0-8-II-eefe2d081a7d49f4b08602f76e50be6a#98e4af335de24263855d3b4f781a9aec)
- [x] Disable balance check for contract accounts
- [x] Move global preferences up so network settings can be modified ([see designs](https://www.figma.com/file/C6XsGAydczT3MxwAwimX4N3c/Onboarding?node-id=164%3A707))

## Upgrade Modal

- [x] Implement flow [PR](https://github.com/aragon/aragon/pull/936)
- [x] Always open showcase on first load (check date is before Oct. 1 + localstorage to avoid opening later)
- [x] Add smaller images for showcase (@owisixseven) [here the Figma files](https://www.figma.com/file/J5JNq0PTZzxSk7QNpw5LFG/Camino-0.8-Upgrade-modal?node-id=0%3A1)
- [x] [Fix internal padding in block text](https://github.com/aragon/aragon/pull/936#issuecomment-526538941)
- [x] Update copy for 0.6 organizations [ref](https://github.com/aragon/aragon/pull/948#issuecomment-527158389)
- [x] Add button to show in Organization detail [ref](https://github.com/aragon/aragon/issues/287#issuecomment-527188998)
- [x] Fix wrong assets (see https://github.com/aragonone/product/issues/133#issuecomment-528123406)

## Global Preferences
- [x] Preferences tabbar has a [double border](https://user-images.githubusercontent.com/4166642/61958186-26710200-afc1-11e9-841e-0c1872fb4155.png), see [fixed](https://user-images.githubusercontent.com/4166642/61958113-05a8ac80-afc1-11e9-85c9-dbca9bde809c.png) ([there's two nested `Bars`, and removing `border-radius` from one of them fixes this](https://user-images.githubusercontent.com/4166642/61958143-148f5f00-afc1-11e9-838f-ef5cbf236ea2.png))
- [x] Global Preferences Help Scout: Fix `z-index`es on components to show Global Preferences overlay on top of Help Scout button
- [x] ~~Add more padding to main `Box`es ( => `24px`)~~ (to be fixed in aragonUI)
- [x] Review Global Preferences Mobile (@dizzypaty sprint 27)
- [x] Update large icons to optimized versions
- [x] App badges in notifications' subscriptions
- [x] Display app custom labels in notifications' filters
- [x] [Notifications polish](https://github.com/aragon/aragon/pull/904#discussion_r321997876)

## Permissions

- [x] Decide on Tag usage for AppCard ([ref](https://github.com/aragon/aragon/pull/899#issuecomment-522357202))
- [x] Replace `ButtonText` with `Link`
- [x] [ref](https://github.com/aragon/aragon/pull/899#issuecomment-527262414)
- [x] Use AppBadges
- [x] Add way to create previously unassigned permissions (and show all available permissions in app detail)
- [x] Add 'view permission' back for burned permissions
- [x] Add 'remove permission' to context menu for non-child entries
- [x] Decide on context menu icons
- [x] `scrollIntoView()` causes weird layout changes

## App Center

- [x] Check copy ([ref](https://github.com/aragon/aragon/pull/928/files#discussion_r318640089))

## Finance

- [x] Empty state for 1st time when there is nothing in the Vault ([designs](https://www.figma.com/file/ZFW8TFOPnPjG0sl36RTRck/Empty-states?node-id=1%3A2696)) ([ref](https://github.com/aragon/aragon-apps/pull/929#discussion_r308142173))
  - [x] Empty Transactions
  - [x] Empty Token balances (designs pending)
- [x] Disabled state buttons ([ref](https://github.com/aragon/aragon-apps/pull/929#discussion_r308150362))
- [x] Info warning designs ([ref](https://github.com/aragon/aragon-apps/pull/929#discussion_r308175309) - [fix](https://github.com/aragon/aragon-apps/pull/929/commits/4836e10a4f7485c71076ff1ebcf9df48852167dc))
- [x] Update DropDown api
- [x] Update with new `Field`
- [x] Update with new `Link`
- [x] Update with new `ButtonText`
- [x] Update to use `useLayout()` instead of `useViewport()`
- [x] Replace `ButtonText` with `Link`
- [x] Update with `AddressBadge`'s `labelStyle`
- [x] Double check copy ([ref 1](https://github.com/aragon/aragon-apps/pull/929#discussion_r314504397), [ref 2](https://github.com/aragon/aragon-apps/pull/929#discussion_r314504863), [ref 3](https://github.com/aragon/aragon-apps/pull/929#discussion_r314725942))

## Tokens
- [x] Update with new `Field`
- [x] Update with new `Link`
- [x] Update with new `ButtonText`
- [x] Replace `ButtonText` with `Link`

## Voting
- [x] CardLayout fix on 1 and 2 items views (items span all available space) (fix on aragonUI)
- [x] Update Badge component to Tag (needs Tag component from aragonUI - [PR](https://github.com/aragon/aragon-ui/pull/434))
- [x] Update Button in Header with new Button interface
- [x] Update DropDown api
- [x] Hide `VoteActions` until we have all the information necessary (to [avoid flickers](https://imgur.com/5Y9DM8u))
- [x] Update with new `Field`
- [x] Update with new `Link`
- [x] Update with new `ButtonText`
- [x] Replace `ButtonText` with `Link`
- [x] App Badge data from aragon.js + filtering (@sohkai)
- [x] Current balance of Token to display with balance at start of vote (@sohkai)
- [x] Add enacted state to status box in vote detail

## Agent

- [x] Background script to remove mocked data (@sohkai, Sprint 27)
- [x] Implement UI
- [x] Test with real Agent (@sohkai Sprint 28)

## aragonUI
- [x] Support `wide` in `DropDown` ([ref](https://github.com/aragon/aragon-ui/issues/429))
- [x] Empty state text styles ([ref](https://github.com/aragon/aragon-apps/pull/929#discussion_r308164322))
- [x] Decide on a text style for buttons ([ref](https://github.com/aragon/aragon-apps/pull/929#discussion_r308164322))
- [x] Modal new styles (mainly overlay is now white, but double check spacing)
- [x] Declare `<Inside name="SidePanel">` in `SidePanel`, display the `TabBar` without the `Bar` if it’s inside of `SidePanel`
- [x] Update `Layout` to provide mechanism to use all the vertical space and take care of overflow/scrolling (double check with [scrolling](https://imgur.com/LTO5gPE) issues) (@bpierre, Sprint 27)
- [x] Update `Field` and `TextInput` for new styles
- [x] Update `Timer` for new styles (text style + spacing)
- [x] Update icons (spacing + stroke width, @owisixseven)
- [x] Consistent padding + margin behaviour for `Box`, `DataView`, `Tab`, etc.
- [x] `AppBadge` (@sohkai Sprint 29)
- [x] Refresh disabled state for Button and DropDown ([designs]
- [x] New toast styles (@AquiGorka Sprint 29)(https://www.figma.com/file/bZ1j7omfhdMCbtFahP3nEJ9B/Client?node-id=665%3A1))
- [x] Empty DataView (handle when there are no entries or when filters result in no entries) ([ref](https://github.com/aragon/aragon-apps/pull/929#discussion_r308171098), [ref](https://github.com/aragon/aragon/pull/899#discussion_r315140913))

**Comment by john-light** [comment]
![agentdash](https://user-images.githubusercontent.com/9424721/64285769-3964e380-cf2a-11e9-8bb1-c7057fc8d3ba.png)


On the 0.8 modal, there is a screenshot on page 6 with three glaring issues:

1. Dash in not an Ethereum token, so should not be shown here
2. The "Connect to CDP" action shows 50 million ANT being deducted, which is more ANT than there even is in existence
3. The fiat values of the tokens are way off e.g. 6 DAI is not worth $300

**Comment by dizzypaty** [comment]
> On the 0.8 modal, there is a screenshot on page 6 with three glaring issues: 
>     1. Dash in not an Ethereum token, so should not be shown here
>     2. The "Connect to CDP" action shows 50 million ANT being deducted, which is more ANT than there even is in existence
>     3. The fiat values of the tokens are way off e.g. 6 DAI is not worth $300

Updated figures and icons on the [Figma file](https://www.figma.com/file/J5JNq0PTZzxSk7QNpw5LFG/Camino-0.8-Upgrade-modal?node-id=0%3A1)
cc @john-light, @sohkai 

Here's the updated mock: 

![showcase](https://user-images.githubusercontent.com/7205369/64298565-4d363700-cf76-11e9-8f87-f9ac179b83fe.png)

cc @delfipolito – I updated this mockup on the New Landing [Figma file](https://www.figma.com/file/SuleuupZMJrCFFFhQGRscNzK/New-landing?node-id=0%3A1). Please change it on the landing page too!

**Comment by john-light** [comment]
I have tried:
- Issuing a token
- Creating a new question vote
- Making a withdrawal from Finance
- Modifying a permission

And each time I am given this error:

> Your transaction wasn't signed and no tokens were sent. Error: “Transaction parameter 'name' is not a valid hex string”

![Screenshot_2019-09-05 Aragon(5)](https://user-images.githubusercontent.com/9424721/64388814-465b0300-d00e-11e9-9824-1fe48d95c76f.png)


And yet as far as I can tell, the transaction did go through:

![Screenshot_2019-09-05 Aragon(6)](https://user-images.githubusercontent.com/9424721/64388825-507d0180-d00e-11e9-8f78-f87b7427e9d4.png)

**Comment by john-light** [comment]
I clicked the link:
- https://rinkeby.aragon.org/#/testorg3.aragonid.eth/?preferences=/notifications/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbklkIjoyOSwic2NvcGUiOiJNQUdJQ0xJTksiLCJpYXQiOjE1Njc3MjMyODgsImV4cCI6MTU2Nzc2NjQ4OH0.OWiJ4UYjOv8_im1T-5a6cgHo2Cq2su2Qq2T3XSIUB2s 

to verify my email, but the org at:

- https://nightly-rinkeby.aragon.org/#/testorg3/0x17e34cff97bbb1eaa2e31af75ffcf2f4098ebca7?preferences=/notifications 

still says “awaiting verification”.

**Comment by john-light** [comment]
Email notifications button says “Sign in”. Which is weird because I’ve never signed up before… maybe given the way that this works this button should say "activate" or something like that?

**Comment by john-light** [comment]
Suggested revision to email notifications panel description:

> Receive email notifications for new app events. For example, whenever a new vote is created or when tokens are issued, you’ll get an email informing you of this activity in your organization. 
>
> You will be asked to enter your email address whenever using a different browser session or device to access your notification subscriptions. This process doesn’t require a password, just for you to confirm your email address whenever you want to activate email notifications. 
>
> The email address you enter here is only used to send you notifications that you have explicitly opted into and will not be shared, rented, or sold for any marketing purposes.

**Comment by john-light** [comment]
Suggested revision to the copy in the email notification activation email:

> You requested that we send you a link to verify your email and opt-in to email notifications. Use the button or link below to verify your email address. This link is only valid for the next 12 hours.

**Comment by john-light** [comment]
Some text box coloring looks a bit “off” in dark mode (e.g. the first yellow box shown below)

![Screenshot_2019-09-05 Aragon(2)](https://user-images.githubusercontent.com/9424721/64389190-99818580-d00f-11e9-9aed-6e9651b43865.png)

**Comment by john-light** [comment]
Can we expect dark mode to work on the apps as well? They currently look light compared to the wrapper:

![Screenshot_2019-09-05 Aragon(1)](https://user-images.githubusercontent.com/9424721/64389250-d9e10380-d00f-11e9-9ca7-51da2711a047.png)

**Comment by john-light** [comment]
"What do you want to do?" text is awkwardly white against a white eagle background in dark mode. Suggestion: Make the eagle a darker blue? (But lighter than the buttons and background)

![Screenshot_2019-09-05 Aragon](https://user-images.githubusercontent.com/9424721/64389270-eebd9700-d00f-11e9-894c-cbf7cceab7a0.png)

**Comment by john-light** [comment]
When I open a vote, the URL does not change. I thought 0.8 would introduce the ability to link directly to a vote?

**Comment by john-light** [comment]
Suggested revision to copy in the Voting app:

> Your vote was cast successfully

**Comment by john-light** [comment]
The voting app notes:

> While the voting period is open, you can change your vote as many times as you wish.

I guess we have decided to continue allowing votes to be changed, rather than making the default that votes cannot be changed?

**Comment by john-light** [comment]
We can make the "Start date" for filters go back no earlier than the beginning of 2018 since there were no organizations on mainnet before then (and the client doesn't work with any rinkeby orgs created before then either)

**Comment by john-light** [comment]
"Remove token" permission does not appear in the "available permissions" for the Tokens app in the Permissions app

![Screenshot_2019-09-05 Aragon(7)](https://user-images.githubusercontent.com/9424721/64389664-98515800-d011-11e9-85f6-dec40a2e576f.png)

**Comment by john-light** [comment]
I created a vote to change the manager of the "Modify quorum" permission on the Voting app to `0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF` and the resulting vote says `ACL: Sets 'Any account' as the manager of the permission 'Modify quorum' in 'Voting'`. 

![Screenshot_2019-09-05 Aragon(8)](https://user-images.githubusercontent.com/9424721/64389803-2dece780-d012-11e9-9c6e-136a522e2aee.png)

At the same time, the option to choose "Any account" as the manager has disappeared from the list of options:

![changemanager](https://user-images.githubusercontent.com/9424721/64389868-6d1b3880-d012-11e9-8676-29aadef8afcf.png)

**Comment by john-light** [comment]
The warning message:

> Do not send ETH or ERC20 tokens to these addresses. If you’d like to deposit funds into this organization, you can do so from [Finance](link-to-finance-app).

could be added to the `Installed Aragon apps` section of the `Organization` system app.

**Comment by sohkai** [comment]
> rinkeby.aragon.org/#/testorg3.aragonid.eth/?preferences=/notifications/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbklkIjoyOSwic2NvcGUiOiJNQUdJQ0xJTksiLCJpYXQiOjE1Njc3MjMyODgsImV4cCI6MTU2Nzc2NjQ4OH0.OWiJ4UYjOv8_im1T-5a6cgHo2Cq2su2Qq2T3XSIUB2s

~~For this you'll need to use `preview`, I don't think the backend knows about `nightly-rinkeby` and redirects you to using `rinkeby`. This should be fixed soon.~~ Now fixed.

> Dark mode

Dark mode will be removed from the release; these are still development previews.

> I thought 0.8 would introduce the ability to link directly to a vote?

This may be included for the release if we can get it in, otherwise it'll be released afterwards.

> I guess we have decided to continue allowing votes to be changed, rather than making the default that votes cannot be changed?

This is a change that will require contract upgrades, and is scheduled for the next release (0.9).

> We can make the "Start date" for filters go back no earlier than the beginning of 2018 since there were no organizations on mainnet before then (and the client doesn't work with any rinkeby orgs created before then either)

All the date pickers (in Finance and Voting) will be re-thought after the release.

> "Remove token" permission does not appear in the "available permissions" for the Tokens app in the Permissions app

Part of the remaining pieces of Permissions; will be done before release.

> I created a vote to change the manager of the "Modify quorum" permission on the Voting app to 0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF and the resulting vote says ACL: Sets 'Any account' as the manager of the permission 'Modify quorum' in 'Voting'.

Did you manually type in `0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF`? This is actually a special value the ACL knows about (as it's a "safe" address) that represents "Any account".

We can add a warning to the panel about this if we detect it though? (See https://github.com/aragon/aragon/issues/969)

**Comment by john-light** [comment]
> @sohkai: Did you manually type in `0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF`? This is actually a special value the ACL knows about (as it's a "safe" address) that represents "Any account".

I copy+pasted the address. The intention is to "discard" or "burn" the permission by assigning management to a burn account, not to give management to any account. Up until now I have been able to burn permissions by assigning them / their management to a burn address like this.

**Comment by john-light** [comment]
The App Badges no longer appear in the Permissions app:

![permissions4](https://user-images.githubusercontent.com/9424721/64456620-a3ae8d00-d0be-11e9-8d7a-f1e5d7b688b5.png)

![permissions3](https://user-images.githubusercontent.com/9424721/64456626-a7421400-d0be-11e9-866a-8cb974056ad0.png)

**Comment by sohkai** [comment]
> I copy+pasted the address. The intention is to "discard" or "burn" the permission by assigning management to a burn account, not to give management to any account. Up until now I have been able to burn permissions by assigning them / their management to a burn address like this.

Ahhh yes, actually the burn address is `0x0000....0001` (and that's the address that gets displayed as "Discarded").

**Comment by john-light** [comment]
@sohkai perhaps we can solve both issues (lack of an "any account" option in the dropdown, and confusion about what address to use to discard) by adding two options to the dropdown: one for "any account" and one for "discard", which will automatically fill in the correct addresses in the background?

Edit: Also, as you suggested earlier, if someone manually enters `0xf...f` we can warn them this will translate automatically to "any account", and if someone manually enter `0x00...01` we can warn them this will translate automatically to "discard".

**Comment by sohkai** [comment]
@john-light These options are available through the panel already though:

<img width="150" alt="Screen Shot 2019-09-09 at 11 22 28 AM" src="https://user-images.githubusercontent.com/4166642/64535786-ca173700-d30f-11e9-8dbc-9890f48e125a.png">

<img width="150" alt="Screen Shot 2019-09-09 at 11 22 45 AM" src="https://user-images.githubusercontent.com/4166642/64535794-ce435480-d30f-11e9-8cb9-2470dce3d3cf.png">

**Comment by john-light** [comment]
> @sohkai: These options are available through the panel already though:

"Remove the manager" doesn't have the same implication as "discard this permission" though does it? From the user guide:

> If a manager removes themselves as a manager of a permission without re-assigning the manager role to another entity, then management of that action defaults to whichever entity manages the “Create permissions” action in the ACL app.

Whereas:

> If the manager of an action is set as 0x0000000000000000000000000000000000000001 then no new manager can be set and permissions granted for that action will be locked forever. 

So "remove the manager" and "discard this permission" really mean two different things, correct?

**Comment by sohkai** [comment]
@john-light Ehh yes, that second screenshot is wrong. We will have an explicit "discard" action for permissions that will open up the "discard" panel (similar to 0.7's) in the Permissions before launch.

You are correct that "remove" and "discard" are two different actions.
