### ISSUE TITLE
Create new templates contracts

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#138]
# Idea
Work on the new templates, both its templates, copies and design for their mini-onboardings.

# Implementation
- [x] Company template [PR](https://github.com/aragon/dao-kits/pull/97) (sprint 22)
- [x] Company with board template [PR](https://github.com/aragon/dao-kits/pull/98) (sprint 22)
- [x] Membership template [PR](https://github.com/aragon/dao-kits/pull/99) (sprint 22)
- [x] Reputation template [PR](https://github.com/aragon/dao-kits/pull/100) (sprint 22)
- [x] Review and merge PRs (sprint 23)
- [x] Review and polish repo [PR](https://github.com/aragon/dao-templates/pull/102) (sprint 23)
- [x] Spec freeze @lkngtn (sprint 23)
- [x] Merge `next` into `master` (sprint 23)
- [x] Remove democracy and multisig templates (sprint 23)
- [x] Update template READMEs and deprecate notion doc (sprint 23)
- [x] Parameterize app settings [#111](https://github.com/aragon/dao-templates/issues/111) [PR](https://github.com/aragon/dao-templates/pull/119) (sprint 23)
- [x] Toggleable agent/vault app [#112](https://github.com/aragon/dao-templates/issues/112) [PR](https://github.com/aragon/dao-templates/pull/121) (sprint 23)
- [x] Helpers to mint tokens [#109](https://github.com/aragon/dao-templates/issues/109) [PR](https://github.com/aragon/dao-templates/pull/122) (sprint 23)
- [x] Optimize app installations [#105](https://github.com/aragon/dao-templates/issues/105) [PR](https://github.com/aragon/dao-templates/pull/125) (sprint 24)
- [x] Add helpers for survey app [#104 ](https://github.com/aragon/dao-templates/issues/104) [PR](https://github.com/aragon/dao-templates/pull/126) (sprint 24)
- [x] _WIP_ Toggleable payroll app [#103](https://github.com/aragon/dao-templates/issues/103) [PR](https://github.com/aragon/dao-templates/pull/124) (sprint 24)
- [x] External audit
- [x] Test deploy to testnet
- [x] Create repos

**Comment by luisivan** [comment]
needs #127

**Comment by luisivan** [comment]
needs aragon/dao-kits#83 aragon/dao-kits#84 aragon/dao-kits#85
