### ISSUE TITLE
App Center documentation

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#16]
# ✅ Idea
## User story
1. As as developer, I want to know which data and assets I need to send for my app to get into the Aragon App Center
2. As a user, I want to read what its app does

## Technical requirements
1. Implement documentation about the app assets in the dev portal

2. Write descriptions for each of the default apps

# ✅ Design

- [x] [Document assets for apps](https://github.com/aragon/design/issues/30)
- [x] [Guidelines on how to create assets for apps](https://github.com/aragon/hack/issues/100): [Figma board](https://www.figma.com/file/XOINhAadQHKCYghNlistQZGc/App-store-asset-guidelines?node-id=0%3A1)

# ✅ Frontend implementation

- [x] Implement [PR](https://github.com/aragon/hack/pull/125) -  [guide on how to submit app assets](https://github.com/aragon/hack/issues/100)
