### ISSUE TITLE
Local labels second iteration

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#176]
# Idea

## Technical requirements
Fix technical debt created from first iteration:

- [ ] [Escape key issue](https://github.com/aragon/aragon/issues/659)
- [ ] [`useIdentity` hook](https://github.com/aragon/aragon/issues/661)
- [ ] [Refactor observable into hook](https://github.com/aragon/aragon/issues/660)
- [ ] [Refactor `AppIFrame` observable into hook](https://github.com/aragon/aragon/issues/662)
- [ ] [Other PR comments](https://github.com/aragon/aragon/issues/672)

**Comment by sohkai** [comment]
Closing; we will track this in the client repo.
