### ISSUE TITLE
HelpScout enhancements next iteration

### ISSUE THREAD

**Issue by AquiGorka** [aragonone/product#189]
Follow up to #115 (WIP PR: https://github.com/aragon/aragon/pull/830)

### Next iteration
  - [ ] [Designs](https://www.figma.com/file/LdjsE4sf6ThhQvlBp1hrFF3Z/Help-Scout)
    - [ ] Desktop
      - [x] Before user opts in for Help & Feedback
      - [ ] Loading screen right after user opts in and `Beacon` is loading
      - [x] After user opts in for Help & Feedback
    - [ ] Mobile
      - [ ] Before user opts in for Help & Feedback
      - [ ] After user opts in for Help & Feedback
  - [ ] Tech debt
    - [ ] Remove `react-helmet` (PR has a first approach at this, needs polishing and sync loading step) ([issue](https://github.com/aragon/aragon/issues/782))
    - [ ] Use `env` var mechanism to set `HELPSCOUT ID` ([issue](https://github.com/aragon/aragon/issues/782))
    - [x] Keep an eye out for [this behaviour](https://github.com/aragon/aragon/issues/889#issuecomment-515237902) but not really in scope for `0.8`
