### ISSUE TITLE
Post 0.8 tasks

### ISSUE THREAD

**Issue by AquiGorka** [aragonone/product#196]
### Client
- [x] Look for and remove deprecated components
- [x] [Ref](https://www.notion.so/aragon/Design-review-0-8-II-eefe2d081a7d49f4b08602f76e50be6a#b48def4f4c924f9da3f403f481748f7b) Update Search inputs functionality (magnifying glass to clear button)
  - [x] [PR](https://github.com/aragon/aragon-ui/pull/601) aragonUI component
  - [x] [PR](https://github.com/aragon/aragon/pull/1099) Custom labels
  - [x] [PR](https://github.com/aragon/aragon/pull/1100) Permissions
  - [x] [PR](https://github.com/aragon/aragon-ui/pull/609) Tokens
- [ ] [Issue](https://github.com/aragon/aragon/issues/1073) Help Scout mobile and onboarding
- [ ] [PR](https://github.com/aragon/aragon-ui/pull/604) [Ref](https://www.notion.so/aragon/Design-review-0-8-items-bf12838cc3874c05811a96722a961ccd#08a1646ce38b47d395905adf8b0d0116)  Implement and update aragonUI component for transaction state
- [ ] Deployment screen: fix header buttons (Pierre)
- [ ] Finish carousel gesture (Pierre)
- [x] Account module popover (Pierre)
- [ ] Favorites: don’t update live on Onboarding + save live on OrgView (Pierre)
- [ ] Refactor routing (Pierre)
- [ ] Finish migrating Wrapper => OrgView (Pierre)
- [ ] Implement transactions manager (Pierre)
- [ ] Deployment screen: contextual errors (Pierre)
- [ ] SignerPanel
  - [ ] RadioList visual refresh ([designs](https://www.figma.com/file/bZ1j7omfhdMCbtFahP3nEJ9B/Client?node-id=525%3A1141))
  - [ ] Show app instance labels (or local identity) in SignerPanel's action descriptions
  - [x] SignerPanel not appearing (its z-index is too low)
  - [ ] SignerPanel should only appear over app view
- [x] Update screenshots for all apps
  - [x] Agent
- [x] [PR](https://github.com/aragon/aragon/pull/1076) The multi-select state should be reseted when importing custom labels from .json
- [x] [PR](https://github.com/aragon/aragon/pull/1077) [Ref](https://www.figma.com/file/QFizPRIWRn6toUp2mPfg5vRE/Global-Apps-and-DAOs-Settings?node-id=815%3A636) 'Search' should be presented as a button and not a field in small viewports. When users tap on it, it should open and expand taking the available width
- [x] [PR](https://github.com/aragon/aragon/pull/1072) Custom Labels implement DataView instead of custom list
- [x] Onboarding: fix full width on the welcome screen ([PR](https://github.com/aragon/aragon/pull/1110))
- [x] Notifications
    - [x] [PR](https://github.com/aragon/aragon/pull/1080) Fix responsive behaviour (see attached images)
    - [x] [PR](https://github.com/aragon/aragon/pull/1079) Fix button icon color (see attachment)

### Client mobile
- [x] Full review for non web3 browsers
- [x] Find out why apps are not loading in mobile Safari after initial load
  - [x] [PR](https://github.com/aragon/aragon-apps/pull/1012/files#diff-e7b7e89ee1e9dda895d3987bea4d8532R63-R67) this seems to be the case for Voting
  - [x] [Issue](https://github.com/aragon/aragon-apps/issues/1014) Error on Tokens
- [x] Global preferences
  - [x] Full review mobile
- [x] [PR](https://github.com/aragon/aragon-ui/pull/599) Toast is loading under global preferences overlay

---

### Apps
- [x] Look for and remove deprecated components
- [ ] [Issue](https://github.com/aragon/aragon-apps/issues/1004) [Ref](https://www.notion.so/aragon/Design-review-0-8-items-bf12838cc3874c05811a96722a961ccd#f64d575da7f94250a8a08193e2ee2e7f) Empty state cards should span vertically just enough above Help Scout button (if user has not opted out)
- [x] [Issue](https://github.com/aragon/aragon.js/issues/395) Dark theme
- [ ] When syncing, how much time is left
- [x] Review apps in Incognito mode. Seems to never stop syncing and apps do not load when account has not been enabled. Same as error from Safari. Tokens and Voting errors.
- [x] [PR](https://github.com/aragon/aragon-ui/pull/602) [Ref](https://github.com/aragon/aragon-ui/pull/594#pullrequestreview-288464583) Copy updates

#### Apps Mobile
- [x] Full review

---

### Finance (and most probably Agent)
- [ ] Full screen filters for mobile
  - [x] [Issue](https://github.com/aragon/aragon-ui/issues/598) Requires new DatePicker
- [x] [Issue](https://github.com/aragon/aragon-ui/issues/598) Update to DatePicker from aragonUI (when it is implemented)
- [ ] [Issue](https://github.com/aragon/aragon-apps/issues/1000) Searching (needs spec)
- [x] [PR](https://github.com/aragon/aragon-apps/pull/1007) Sorting for the table (locally in app, eventually should be implemented in aragonUI although this is quite a handful)
- [ ] Summary bar (needs new component from aragon UI)
- [ ] [Issue](https://github.com/aragon/aragon-apps/issues/1015) [Ref](https://github.com/aragonone/product/issues/195#issuecomment-531741566) Fix table layout for long descriptions
- [x] Autocomplete use aragon UI component

#### Finance Mobile
- [x] [PR](https://github.com/aragon/aragon-ui/pull/608) Fix DropDown in new deposit (see attachment below)
- [x] [PR](https://github.com/aragon/aragon-ui/pull/608) New Transfer Deposit on Mobile: DropDown Popover does not scroll so it is not possible to select one of the first tokens nor close the list options without choosing one.

---

### Voting
- [ ] [Issue](https://github.com/aragon/aragon-apps/issues/1018) Filters for mobile
- [x] [Ref](https://www.dropbox.com/s/vhz48jz3t0h1z36/VOTE_DETAILS.mov?dl=0) Animate card on votes list: when user hovers display you voted
- [ ] Display app custom labels in app filter
- [ ] Current balance of Token to display with balance at start of vote from aragon.js
- [ ] Share a vote URL
  - [ ] Share quick copy without popover or copy with popup
- [ ] Tooltips (needs illustrations)
- [ ] [Issue](https://github.com/aragon/aragon-apps/issues/1001) Search
- [ ] [Issue](https://github.com/aragon/aragon-apps/issues/1002) [Ref](https://www.notion.so/aragon/Design-review-0-8-items-bf12838cc3874c05811a96722a961ccd#2fcd62c74601462995ea1c9544170687) Iterate on label for passed votes
- [x] [Issue](https://github.com/aragon/aragon-ui/issues/598) Update to DatePicker from aragonUI (when it is implemented)
- [x] CardLayout fix on 1 and 2 items views (items span all available space)
- [x] Timer component update spacing

---

### Tokens
- [x] [Issue](https://github.com/aragon/aragon-apps/issues/1014) Network null prevents UI rendering
- [x] [PR](https://github.com/aragon/aragon-apps/pull/1016) Long custom labels overflow data view

---

### aragonUI

- [x] [Issue](https://github.com/aragon/aragon-ui/issues/598) DatePicker
- [x] `DropDown` disable active state (https://github.com/aragon/aragon-ui/issues/443)
- [x] [PR](https://github.com/aragon/aragon-ui/pull/605) [Issue](https://github.com/aragon/aragon-ui/issues/603) DataView compact view heading padding

---

### Attachments

Notifications:

<img src="https://user-images.githubusercontent.com/3072458/64942781-41961a80-d86a-11e9-9933-5d60ef7133b1.jpg" height=200>
<img src="https://user-images.githubusercontent.com/3072458/64942786-435fde00-d86a-11e9-8b36-db245098fd94.jpg" height=200>

Finance:

<img src="https://user-images.githubusercontent.com/3072458/64942794-48249200-d86a-11e9-817a-dd3f6563ca9f.jpg" height=200>

**Comment by sohkai** [comment]
Going to close this; all the other issues have been de-prioritized and moved into separate issues.
