### ISSUE TITLE
Local identity (custom labels)

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#2]
# ✅ Idea
## User story
As as user, I want to see names so I can interact with entities knowing who they are to me.

Related issues: [1](https://github.com/aragon/aragon/issues/620)

## Technical requirements
As an intermediate solution for the full Aragon identity experience, we will allow people to create custom local labels to identify addresses that represent different members of the organization.

These custom labels will be displayed in place of the addresses and can be added directly from the address badge popover or importing/exporting a .json file that then can be shared with the members of your organization.

- This data will only be stored locally on the users’ device
- Applications will have read-only access to these labels
- Applications will be able to request editing, but that will trigger the Aragon client to open a modal and let the user edit them from the parent context, for security's sake
- This data will be accessible across all your organizations as part of the global preferences. The user will also be able to select exporting per organization, which will just export a sub-group of all the labels that were created in a particular organization

## Summary

This functionality will allow the user to know who they are interacting with, while keeping implementation complexity very low.

# ✅ Design
[Figma board](https://www.figma.com/file/QFizPRIWRn6toUp2mPfg5vRE/Global-preferences-%26-custom-labels?node-id=0%3A1)

# ✅ Frontend implementation
[Working branch](https://github.com/aragon/aragon/tree/feature/custom-labels) | [PR](https://github.com/aragon/aragon/pull/630)

- [x] Review and merge ongoing PRs

# Future iteration
- [ ] [Escape key issue](https://github.com/aragon/aragon/issues/659)
- [ ] [`useIdentity` hook](https://github.com/aragon/aragon/issues/661)
- [ ] [Refactor observable into hook](https://github.com/aragon/aragon/issues/660)
- [ ] [Refactor `AppIFrame` observable into hook](https://github.com/aragon/aragon/issues/662)
- [ ] [Other PR comments](https://github.com/aragon/aragon/issues/672)
