### ISSUE TITLE
aragonUI: 1.0

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#210]
# Idea

Release aragonUI 1.0, with aragonDS.

## Progress

- [x] @bpierre to review last few components (Sprint 35)

### Sprint 37

- [x] @owisixseven @bpierre to finish dark theme (Sprint 37)
- [x] @bpierre to update component documentation (Sprint 37)
- [x] @bpierre to update migration documentation (Sprint 37)
- [x] @bpierre to write release blog post (Sprint 38)
- [x] @john-light to review blog post (Sprint 39)
