### ISSUE TITLE
SDK: v7

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#222]
# Idea

As a developer, I want aragonCLI's code to be easy to understand, maintain, and build on top of.

Currently, many tasks that look like "low hanging fruit", e.g. those in https://github.com/aragon/aragon-cli/issues/827, are actually quite difficult to develop for a variety of reasons:

- Lots of duplicated code
- No clear separation of concerns
- Lack of tests

We will take this chance to greatly reduce technical debt, while attempting to maintain the same external interface.

**Appetite**: 4 weeks (Nov. 4 to Nov. 22, Dec. 2 to Dec. 6)
**Outcome**: A stable release of aragonCLI v7

## Related documents

- [Taskforce tracking doc](https://docs.google.com/document/d/14wqx_hEif6M_8g1fqNctdsVSbjVN7InYblr04wZ7CyQ)

## Progress

- [x] Forum post announcing the creation of the working group (Sprint 36)
- [x] Move chat to a public channel (Sprint 36)
- [x] Map existing aragonCLI user journeys #852: https://github.com/aragon/aragon-cli/issues/852 - survery results => https://docs.google.com/forms/d/18iviVKBZvGi1pmzm5kMHYHYt9K86G7dvvmOtDPTzqC4/viewanalytics
- [x] Set up branch strategy for SDK v7 refactors #851: https://github.com/aragon/aragon-cli/issues/851  (Sprint 36)
- [x] Close low hanging fruit PRs before SDK v7 refactors begin #853: https://github.com/aragon/aragon-cli/issues/853  (Sprint 36)
- [x] Make a proposal for separating the CLI's interface from its logic #849: https://github.com/aragon/aragon-cli/issues/849  (Sprint 36) https://github.com/aragon/aragon-cli/pull/856
- [x] Refactor: separate logic from commands (mono issue) https://github.com/aragon/aragon-cli/issues/858 (Sprints 36-39)
  - [x] Complete initial round of refactoring (Sprint 39)
- [x] Finalize initial v7 release (https://github.com/aragon/aragon-cli/issues/981)
  - [x] Consolidate test and code structure
  - [x] Consolidate initial version of API
  - [x] Write announcement blog post

**Comment by dapplion** [comment]
Having onboard to aragonCLI recently, I want to express that it was difficult to understand the code overall. The improvement proposed in this issue to separate logic and commands + unit test them would have helped me a lot to understand the code quicker, and I'm sure it will be very useful for future contributors :heart: :fireworks:.

However, one of the most annoying issues for me when understanding this codebase is that `listr` context variables are not typed nor documented. Since they are mutated on runtime, it's very hard to know what value they may have after running through the middlewares and previous commands. This may not be an issue for developers with code experience in the CLI, but for newcomers wanting to do a small contribution a list like the one in `commands/apm_cmds/publish.js` is daunting
```
exports.runPrepareForPublishTask = ({
  reporter,

  // Globals
  cwd,
  web3,
  network,
  module,
  apm: apmOptions,
  silent,
  debug,

  // Arguments

  /// Files
  publishDir,
  files,
  ignore,

  /// Http
  httpServedFrom,

  /// Storage
  provider,

  /// Conditionals
  onlyArtifacts,
  onlyContent,
  http,

  // Context
  initialRepo,
  initialVersion,
  version,
  contractAddress,
  deployArtifacts,
})
```

@sohkai @0xGabi let me know if you feel this is a relevant issue that may be in scope for this Epic and I can propose some solutions.

**Comment by 0xGabi** [comment]
You are right. The publish command is too complex and not organized enough. If you have some solutions to propose we should definitely include them. One interesting idea particular of the publish flow is separate the concerns of aragonPM and local development on two separate commands

**Comment by 0xGabi** [comment]
@ajsantander I removed you from this issue cause you already made your part, thanks a lot for the help so far 🙏
