### ISSUE TITLE
aragon.org: setup internationalization infrastructure

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#233]
See https://github.com/aragonone/product/issues/229.

------

### Tasks

- [x] Design internationalization experience
- [x] Decide on a React internationalization library to use
- [x] Decide on how to send tracking information to Matomo about user's declared language
  - e.g. URL query parameters, redirect to subdomain, manually send tracking event
- [x] Integrate internationalization infrastructure
- [x] Set up automated workflow for strings to translate

### Progress
