### ISSUE TITLE
ANJ Uniswap integration

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#264]
# Idea
## User story
As as user, I want to activate ANJ with multiple tokens through Uniswap.

## Tasks

- [x] Finish wrapper contract @bingen 
  - Decide whether we want one or two contracts for Phase 1 + Phase 2
- [x] Test on Rinkeby @bingen 
- [ ] Audit?
- [x] Deploy on Mainnet
- [x] Design token selector for anj.aragon.org @owisixseven
- [x] Integrate with anj.aragon.org @Evalir
