### ISSUE TITLE
Organization Agreements

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#265]
# Idea
## User story
As as user, I want my organization's decisions to be insured by the Court.

## Tasks

- [x] Technical exploration @izqui 
  - [x] Iterate into public version for feedback
- [ ] User research @dizzypaty 
  - [x] Schedule design workshop
- [x] Technical specification
- [ ] Contract implementation
