### ISSUE TITLE
Jurors dashboard: usability research

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#266]
# Idea

Conduct one round of usability testing for the jurors.

## Tasks

- [x] Define test plan
- [x] Set up Rinkeby test court with frontend
- [x] Set up automated services on Rinkeby
- [x] Action items from feedback
