### ISSUE TITLE
ANJ 150 t-shirts

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#273]
# Idea

Build a web store to ship ANJ 150 t-shirts.

## Tasks

- [x] Finalize t-shirt design
- [x] Build web store
- [x] Integrate with our collected emails / obtain missing emails
