### ISSUE TITLE
Organization Agreements: contract POC

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#305]
**GitHub [issue](https://github.com/aragon/aragon-apps/issues/1132) and [PR](https://github.com/aragon/aragon-apps/pull/1133)**

### TODO:
- [x] Initial PoC (@facuspagnuolo)
- [x] Review PoC (@izqui)
- [ ] Review PoC (@sohkai)
- [ ] Address feedback from reviews (@facuspagnuolo)
- [x] Add technical documentation (@facuspagnuolo)
- [x] Publish to Rinkeby aragonPM
