### ISSUE TITLE
Tokens: vesting UI

### ISSUE THREAD

**Issue by sohkai** [aragonone/product#306]
# Idea
## User story
As as user, I want to see the vestings of a holder.

See kickoff notes: https://www.notion.so/aragon/Token-Vesting-UI-652d4a364e054105b980aa12071367ae

## Tasks

- [ ] Finalize designs
- [ ] Listen and reduce vesting information from events in background script
- [ ] aragonUI additions (e.g. clickable DataView row when in table mode)
- [ ] Detail view of each holder
- [ ] Path for each holder
