### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#4]
# ✅ Idea
## User story
As as user, I want to be able to view and interact with my organizations from anywhere. As a user, my favorite way of interacting on the go is with a smartphone. Therefore, I want Aragon on my phone.

## Technical requirements
Implement responsive views across all frontend. See more requirements on the PR.

## Summary

By implementing responsive across all the frontend, the user will be able to use Aragon on their phone and view organizations. If they use a Web3 provider, they will also be able to interact with the organization.

# ✅ Design
Figma boards:
- [x] [Token Manager](https://www.figma.com/file/FDIfdynDFqeJ9DrSEVMbTY3z/Token-Manager?node-id=0%3A1)
- [x] [Payroll](https://www.figma.com/file/VhkSnRsC6fuGlZZxI487isRF/Payroll)
- [x] [Survey](https://www.figma.com/file/Zda2OxMBAzhPP1M9NNFK4GUG/Survey?node-id=0%3A1)
- [x] [Finance](https://www.figma.com/file/QmMPLYA2e2fs3XrJDctCiUQQ/Finance?node-id=0%3A1)
- [x] [Voting](https://www.figma.com/file/0p9Jrf86JpJjQNBfsdEI52Sq/Voting?node-id=0%3A1)

# ✅ Frontend implementation

Sprint 7:
- [x] Finish burger menu [ref](https://github.com/aragon/aragon/pull/539#issuecomment-446598666) [PR](https://github.com/aragon/aragon.js/pull/259) [PR](https://github.com/aragon/aragon/pull/651) [PR](https://github.com/aragon/aragon-apps/pull/717) [PR](https://github.com/aragon/aragon-apps/pull/765) [PR](https://github.com/aragon/aragon-apps/pull/764)

---

- [x] Menu panel
  - [x] Menu Panel communication with apps [PR](https://github.com/aragon/aragon/pull/539)
  - [x] Iframe apps using menu panel [PR](https://github.com/aragon/aragon-apps/pull/606)
- [x] Side panel [PR](https://github.com/aragon/aragon-ui/pull/280)
- [x] Onboarding
  - [x] Start screen [PR](https://github.com/aragon/aragon/pull/581)
- [x] Review apps one by one to see which ones might need work for mobile
    - [x] Voting [PR](https://github.com/aragon/aragon-apps/pull/617)
    - [x] Finance [PR](https://github.com/aragon/aragon-apps/pull/619)
    - [x] Token Manager [PR](https://github.com/aragon/aragon-apps/pull/612)
    - [x] Permissions [PR](https://github.com/aragon/aragon/pull/583)
    - [x] Apps [PR](https://github.com/aragon/aragon/pull/554)
    - [x] Settings [PR](https://github.com/aragon/aragon/pull/548)

-------------

Additional implementation iteration (following initial implementation above):

-  [x] Fix Menu Panel shadow similar to Signer Panel shadow [PR](https://github.com/aragon/aragon/pull/605)
- [x] Enable swipe to open/close for the Menu Panel [PR](https://github.com/aragon/aragon/pull/606)
- [x] Fix `BreakPoint` API and Component to avoid re-rendering every time screen size changes [ref](https://github.com/aragon/aragon-ui/issues/281)
  - [x] aragon/aragon [PR](https://github.com/aragon/aragon/pull/601)
  - [x] apps [PR1](https://github.com/aragon/aragon-apps/pull/671) [PR2](https://github.com/aragon/aragon-apps/pull/672) [PR3](https://github.com/aragon/aragon-apps/pull/673)
- [x] Update app's layout to `AppView` from `aragon/ui` [PR](https://github.com/aragon/aragon/pull/615)
- [x] Regarding changes to iframe apps: common Components & changes can be moved to `aragon/ui` (`MenuButton` and borderless `TableCell`)
  - [x] aragon/aragon [PR](https://github.com/aragon/aragon/pull/615)
  - [x] aragon/apps
- [x] Update `MenuButton`s to use `ButtonIcon` component and update alignment with layouts [PR](https://github.com/aragon/aragon-ui/pull/311)
- [x] Fix Permissions title not being animated on navigation [PR](https://github.com/aragon/aragon/pull/615)
- [x] Fix Permissions EmptyBlock margin [PR](https://github.com/aragon/aragon/pull/615)
- [x] Fix button's `:focus-visible` [PR](https://github.com/aragon/aragon-ui/pull/311)
- [x] Permissions move Buttons to UI [PR](https://github.com/aragon/aragon/pull/615)
- [x] Move `ToggleFiltersButton` to `aragon/ui` [ref](https://github.com/aragon/aragon-apps/pull/619#discussion_r249410260) [PR](https://github.com/aragon/aragon-ui/pull/344)
- [x] Use `FocusVisible` in `ToggleFiltersButton` [ref](https://github.com/aragon/aragon-apps/pull/619#discussion_r249415017) (done since [`ButtonIcon`](https://github.com/aragon/aragon-ui/pull/285) is used)
- [x] Review iframe screen sizes < 768 within desktop screens < 768 + 219 as the MenuButtons appear and they shouldn't [ref](https://github.com/aragon/aragon-apps/pull/619#issuecomment-457643424)  [PR](https://github.com/aragon/aragon-apps/pull/717) [PR](https://github.com/aragon/aragon-apps/pull/765) [PR](https://github.com/aragon/aragon-apps/pull/764)
- [x] Fix issue with `breakpoint` using iframes proportions instead of `window.parent`

-------------

- [ ] Responsive Notifications panel [issue](https://github.com/aragonone/product/issues/21)
- [ ] Show more on mobile (click twice) removes all transfers. update: Only happens on iOS. Weird behaviour: add eth filter, then remove it, then click on show older transfers and the bug does not happen. [issue](https://github.com/aragon/aragon-apps/issues/768)
- [x] Finance fix filters margin [ref](https://github.com/aragon/aragon-apps/pull/619#pullrequestreview-197152789) [PR](https://github.com/aragon/aragon-apps/pull/767)
- [ ] Full responsive Onboarding [issue](https://github.com/aragonone/product/issues/40)
- [x] Discuss and plan a more "secure" implementation of communication between apps and client (to avoid misuse of fullscreen) [ref](https://github.com/aragon/aragon/pull/539#issuecomment-446598666) [PR](https://github.com/aragon/aragon.js/pull/259) [PR](https://github.com/aragon/aragon/pull/651) [PR](https://github.com/aragon/aragon-apps/pull/717) [PR](https://github.com/aragon/aragon-apps/pull/765) [PR](https://github.com/aragon/aragon-apps/pull/764) 
- [ ] Voting was not rendering full cards while getting the data [issue](https://github.com/aragon/aragon-apps/issues/769)
- [ ] Fix scroll to top on Permissions app [issue](https://github.com/aragon/aragon/issues/681)
- [ ] Fix/discuss two grid columns for Permissions app and margin [ref](https://github.com/aragon/aragon/pull/583#issuecomment-458255972) [issue](https://github.com/aragon/aragon/issues/680)
- [ ] Fix long times for voting overflow [issue](https://github.com/aragon/aragon-apps/issues/638#event-2099323617)
