### ISSUE TITLE
Global kill-switch

### ISSUE THREAD

**Issue by facuspagnuolo** [aragonone/product#54]
# Idea
## User story

- As an application developer, I want to be able to notify our users that a critical event happened and that they must upgrade their applications to the latest version to avoid being affected. 

- As a security auditor, I want to inform users of a potential issue with a contract they're using and recommend them from using the current version of the contract.

- As as user, I want to be able to choose whether to switch my application off upon being notified that an upgrade is strongly recommended.

## Implementation

- [x] Research possible approaches - [doc](https://www.notion.so/aragon/Kill-switch-14fb6e4ac17049dfbe69c2b97404bd79) (sprint 12)
- [x] Proof of concept [PR 516](https://github.com/aragon/aragonOS/pull/516) (sprint 12) 
- [x] Initial review and discuss edge cases (sprint 13)
- [x] MVP implementation of aragonOS contracts - [PR 518](https://github.com/aragon/aragonOS/pull/518) (sprint 13)
- [x] Review recoverability proposal described [here](https://github.com/aragon/aragonOS/issues/523) (sprint 14, sprint 15)
- [x] Sync on scope for KillSwitch and recoverability (sprint 16)
- [x] Emergency upgrades path proposal - [PR](https://github.com/aragon/aragonOS/pull/533) (sprint 18)
- [ ] Final review
- [ ] Discuss terminology and write inline documentation

-----------

Exposing this to users through an UI implementation will likely follow as a separate issue.

**Comment by luisivan** [comment]
Next step: Have a call to discuss edge cases

**Comment by luisivan** [comment]
Next step: @izqui and @sohkai to make a final call on the implementation during Sprint 14

**Comment by sohkai** [comment]
This was researched and an idea spiked. As we won't be making protocol-level changes at this moment, we will stage and re-consider this in the future.
