### ISSUE TITLE
0.7 remaining

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#55]
**Activity panel**
- [x] PR review feedback (⛰️ ↘️, Daniel)
- [x] Activity panel pretransaction support (⛰️ ↘️, Daniel)
- [x] Activity panel polish (↗️⛰️↘️, Pierre)
  - [x] Layout bug
  - [x] Shorten addresses / use Identity Badge

**App Center**
- [x] List with items: https://github.com/aragon/aragon/pull/625#issuecomment-483056285 (↗️ ⛰️, Brett / Pierre)
- [x] Handle screenshots
- [x] Use `AppIcon` (so the new icons get rounded) (⛰️ ↘️, Pierre)
- [x] Adding updated icons (⛰️ ↘️, Pierre / etc.)
- [x] Release notes / source code URLs in the upgrade panel (⛰️ ↘️)

**Connect account**
- [x] PR review feedback (⛰️ ↘️, Daniel)
- [x] Fix custom label when changing account (⛰️ ↘️, Daniel) 

**Upgrade modal**
- [x] Layout (↗️ ⛰️, Pierre)

**Payroll**
- [x] Merge contracts (⛰️ ↘️, Facu / Brett)
- [x] Fix usage of price feed (https://github.com/aragon/aragon-apps/issues/792) (⛰️ ↘️, Facu / Brett)
- [x] Deploy PPF on staging (⛰️ ↘️, Jorge)

**Contracts**
- [x] Release aragonOS (⛰️ ↘️, Brett)
- [x] Update apps (⛰️ ↘️, Brett)
- [x] Publish apps to npm (⛰️ ↘️, Brett)
- [x] Update dao-kits (⛰️ ↘️, Brett)
- [x] Release new contracts on staging (⛰️ ↘️, Jorge / Brett)

**Misc.**
- [x] Transaction pathing (https://github.com/aragon/aragon/issues/520) (↗️ ⛰️, Brett)
- [x] Fix multiple calls scripts rendering (https://github.com/aragon/aragon.js/issues/260) (⛰️ ↘️, Brett)
- [x] Voting clarifications (https://github.com/aragonone/product/issues/42) (↗️ ⛰️, Pierre)
- [x] Quick fixes for Finance date
- [x] Voting voter state caching / improved update mechanism (↗️ ⛰️, Brett / Daniel)
- [x] Update app icons to latest ones submitted by @owisixseven 
- [x] Center Preferences close button so it's not on the far right
- [x] Upgrade `@aragon/ui` on every app (⛰️ ↘️ @bpierre)
