### ISSUE TITLE
Identities autocomplete

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#59]
# Idea

Autocomplete the identities when tying into address inputs, by getting the local identities saved in the browser.

# Design
[Figma board](https://www.figma.com/file/Ffxzu9CDt8KWluyYOVELUnNW/0.7-Usability-testing-issues?node-id=110%3A145)

# Implementation
- [x] Kickoff sync (sprint 13)

## aragonAPI
- [x] https://github.com/aragon/aragon.js/pull/308

## apps
- [ ] Token Manager https://github.com/aragon/aragon-apps/pull/862
- [ ] Finance https://github.com/aragon/aragon-apps/pull/877
- [ ] Permissions https://github.com/aragon/aragon/pull/820

**Comment by dizzypaty** [comment]
WIP Figma file: https://www.figma.com/file/Ffxzu9CDt8KWluyYOVELUnNW/0.7-Usability-testing-issues?node-id=110%3A145

**Comment by luisivan** [comment]
Next step: Kickoff call during Sprint 13

**Comment by dizzypaty** [comment]
# Search auto-complete utility 

## Behavior 

One of the key principles in HCI (Human Computer Interaction) is **recognition over recall**: people are better at recognizing things they have previously experienced than they are at recalling them from memory. An auto-complete search utility transforms a recall problem into one of recognition. 

Auto-complete makes the most sense when the choices are based on a controlled list, i.e., a finite list of custom labels, addresses and so on. 

This search utility should auto-complete ETH addresses, custom labels, ENS domains or others future identity providers strings. 

It should display the available list of items that matches the first character of the string entered by the user right after the first keystroke, if a match is found.

ℹ️ **Important note:** for auto-completing the ETH addresses, we will not show any matching item until users have typed at least the 3 first characters, i.e., `0xa`. This way, we will avoid scrollbars and we’ll keep the list manageable. 

The autocomplete utility should remain unobtrusive, so users can still enter a query in full if they choose. **It should also support keyboard navigation:** Users should be able to select an item from the list navigating with the up and down arrows and hitting the enter key.

Any auxiliary data in the suggestion – such as an ETH account when typing custom labels or vice versa – should be styled differently ([see visual assets](https://github.com/aragonone/product/issues/76#issuecomment-488029438)) from the actual suggested search terms. Otherwise, the user won’t be able to tell at a glance what is (and isn’t) part of the suggested search item. 

## Designs

#### Custom label auto-complete

Default state of the panel: first field focused when panel is opened:

![WebApp-1366px - main-view@2x-3-2.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/a2ef5a23-76a0-4928-a481-eed4c61eaaf4)

User starts typing the first character and we show the list of matching items:

![WebApp-1366px - main-view@2x.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/3de3efa8-4955-4c98-bdb4-5d164a780f94)

User selects (using keyboard or pointer) one of the items in the list of autocomplete results: 

![WebApp-1366px - main-view@2x-9.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/5425306b-7255-455f-8413-170a4ab1c84b)

Alternatively, users can continue typing characters and the list should update and reflect the matching items based on the new string:

![WebApp-1366px - main-view@2x-1.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/0b915f36-7580-48b8-9efa-8f1339f6e838)

Field displays the selected item:

![WebApp-1366px - main-view@2x-7.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/dc77fca7-d85e-4655-a9ca-b732ea72676b)

When clicking on the field again after a selection has been made, we should display the selected autocomplete item with the auxiliary text, in this case, the address: 

![WebApp-1366px - main-view@2x-2.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/d5b58877-3d80-4ab9-be7b-04e37bf9406c)

#### Address auto-complete
Follow same behavior as specified above, with the exception of the important note for ETH addresses (**Important note:** for autocompleting the ETH addresses, we will not show any matching item until users have typed at least the 3 first characters, i.e., `0xa`. This way, we will avoid scrollbars and we’ll keep the list manageable).

![WebApp-1366px - main-view@2x-10.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/4e7350f5-baae-4c81-8525-4ed2519b2ee9)

![WebApp-1366px - main-view@2x-4.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/8dd9a7f2-f9e8-4e5b-bab7-a7a34068586c)

![WebApp-1366px - main-view@2x-6.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/f0d96719-5000-4028-97cf-3edfac6fc05f)

#### ENS domain auto-complete

Follow same behavior as specified for custom labels. The autocomplete should display a list of items that match any part (begging, middle or end) of the string, in this example: `.eth`

![WebApp-1366px - main-view@2x-8.png](https://images.zenhubusercontent.com/5c0e82b4cd03b2349870e421/76bda520-7ca6-4fe6-b1b2-9d6ad37c3e2b)

## Figma page with visual assets
https://www.figma.com/file/Ffxzu9CDt8KWluyYOVELUnNW/0.7-Usability-testing-issues?node-id=42%3A12265

**Comment by AquiGorka** [comment]
On the technical side, after careful considerations it was agreed to expose a search method that will resolve its input to addresses.
The method will be exposed via `aragonAPI` and can be executed from the apps' context.
The apps will then be responsible to render the returned information.

**Comment by sohkai** [comment]
@dizzypaty We were also considering limiting the number of results returned from the API to a reasonable number (e.g. max 10), so as to not flood the dropdown and also provide results a little bit faster.

A few notes:

- Wanted to confirm the search criteria: the search text can match any substring inside a label (rather than just the prefix)?
- We would likely want to consider ENS integration in a second iteration. It wouldn't be possible to search for substrings (unless the associated label is an ENS domain), but we could attempt to reverse resolve an ENS domain to its address and display that as a single option.
- I'd consider `0x...` to "switch" the autocomplete mode to searching for addresses. If a user for some reason uses `0x...` as their label, it won't be found.

**Comment by luisivan** [comment]
@sohkai I'd say a user choosing 0x as their label is quite an edge case, but it can certainly happen if for example someone is interacting with 0x (the project)

**Comment by 2color** [comment]
> On the technical side, after careful considerations it was agreed to expose a search method that will resolve its input to addresses.
The method will be exposed via aragonAPI and can be executed from the apps' context.
The apps will then be responsible to render the returned information.


Does that mean that every app will render the actual autocomplete and that we will probably introduce a new autocomplete input in `aragon-ui` that we will plug into the api, but unlike the identity modifications, this will actually be handled by the app?

**Comment by sohkai** [comment]
Yes, the API will still be handled by the wrapper, but it will be up to the app to correctly handle the responses and show them, similar to how the local identities are currently displayed in app `IdentityBadge`s.

**Comment by luisivan** [comment]
@sohkai wrapper -> Aragon client 🙃

**Comment by dizzypaty** [comment]
Hey @sohkai 

> Wanted to confirm the search criteria: the search text can match any substring inside a label (rather than just the prefix)?

Yes, we should display a limited number of results (7-11 max.) when one or several substrings (prefix, suffix,etc.) are found within the larger string or input text. 

> We would likely want to consider ENS integration in a second iteration. It wouldn't be possible to search for substrings (unless the associated label is an ENS domain), but we could attempt to reverse resolve an ENS domain to its address and display that as a single option.

Sounds good to me.

> I'd consider 0x... to "switch" the autocomplete mode to searching for addresses. If a user for some reason uses 0x... as their label, it won't be found.

Not sure I understand why. Instead of this being a different autocomplete mode, could not just have special rules for prefixes that start with `0x`?

**Comment by sohkai** [comment]
> Not sure I understand why. Instead of this being a different autocomplete mode, could not just have special rules for prefixes that start with 0x?

This is mainly with how the data is arranged, we store the addresses as keys and their labels as values, so if we see `0x` I was thinking we could just switch to searching the keys (to only get addresses).

**Comment by AquiGorka** [comment]
@luisivan question about searching:

>It should display the available list of items that matches the first character of the string entered by the user right after the first keystroke, if a match is found.

Should we return results only when they comply with `label.indexOf(searchTerm) === 0` (meaning only when the label starts with the searched term or should we include any label where the searched term appears anywhere within the label (`label.indexOf(searchTerm) > -1`)?

**Comment by sohkai** [comment]
@AquiGorka 

From https://github.com/aragonone/product/issues/59#issuecomment-493513431

> Yes, we should display a limited number of results (7-11 max.) when one or several substrings (prefix, suffix,etc.) are found within the larger string or input text.

It sounds like the latter (`label.indexOf(searchTerm) > -1`).
