### ISSUE TITLE
Payroll

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#6]
# ✅ Idea
## User story
As as employee, I want to get paid in real time and by clicking a button. I also want to be able to receive stable assets such as Dai to avoid volatility. I want to receive my payroll in real time, not even wait until the end of the month.

As an employer, I want to pay my employees without manual intervention. I want to be able to change their salaries and addresses they will receive it to, and also stop payroll if necessary.

## Technical requirements
- Smart contracts that interact with the Finance app and let the employer authorize the Payroll app to perform payments
- Support form ERC20 tokens
- Beautiful UI for both employees and employers

## Summary

By implementing smart contract-based payroll as an Aragon app, employees can receive their payroll with a click, and employers can just authorize the app to withdraw funds, and then completely forget about doing payroll ever again.

# ✅ Design
[Figma board](https://www.figma.com/file/VhkSnRsC6fuGlZZxI487isRF/Payroll)

# 🔜 Frontend implementation
[Working branch](https://github.com/aragon/aragon-apps/pull/851)

- [x] Old PRs (from Protofire)
- [ ] [Draft PR for new UI](https://github.com/aragon/aragon-apps/pull/851)
  - [ ] WebWorker
  - [ ] Render tables
- [ ] Add warning indicating that it doesn't work on mobile

# 🔜 Contracts implementation

- [x] Sanity check Rinkeby deployment of PPF
- [x] Document PPF deployment ([issue](https://github.com/aragon/deployments/issues/55))
- [x] Update Payroll [1](https://github.com/protofire/aragon-apps/pull/113), [2](https://github.com/aragon/aragon-apps/pull/610), [3](https://github.com/aragon/aragon-apps/pull/729), [4](https://github.com/aragon/aragon-apps/pull/744)
- [x] Improve Payroll tests and coverage
- [x] @izqui to redeploy PPF and document ([issue](https://github.com/aragon/deployments/issues/55))
- [x] Freeze Payroll contract for review
- [x] Audit response (sprint 20; @sohkai)
- [x] Audit fixes (sprint 20; @facuspagnuolo)
  - [x] Hardcode role constant values [PR 899](https://github.com/aragon/aragon-apps/pull/899)
  - [x] Add owed salary getter function [PR 900](https://github.com/aragon/aragon-apps/pull/900)
  - [x] Remove allowed tokens [PR 901](https://github.com/aragon/aragon-apps/pull/901)
  - [x] Use PPF rate precision [PR 902](https://github.com/aragon/aragon-apps/pull/902) & [PR 28](https://github.com/aragon/ppf/pull/28)
  - [x] Add payroll remainders as accrued salary [PR 903](https://github.com/aragon/aragon-apps/pull/903)
  - [x] Support employee's min acceptable exchange rates [PR 904](https://github.com/aragon/aragon-apps/pull/904)
- [x] Finalize audits

# Future

- [ ] Investigate other price feed mechanisms if users are interested (e.g. [ETHDAI](https://github.com/aragon/ppf/issues/15), [Polaris](https://github.com/aragon/ppf/issues/16))

**Comment by luisivan** [comment]
@sohkai can you post an update on this? Has the PPF check been completed?

**Comment by sohkai** [comment]
I believe @izqui has deployed PPF to Rinkeby, but still waiting for it to be documented: https://github.com/aragon/deployments/issues/55.

**Comment by sohkai** [comment]
@facuspagnuolo and I spoke offline and decided to move the alternative price feed implementations as later items, if we see users starting to request them. We can communicate this during the soft launch, and see if they'd actually want to use the "low maintenance" feeds before building them.

**Comment by sohkai** [comment]
Closing; 1hive will take over work on payroll.
