### ISSUE TITLE
Read-only UI for Agent app

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#81]
# Idea
## User story
Agent allows Aragon organizations to interact with other contracts as its own entity. However, Agent is just accessible through aragonCLI right now. As a user, I want to view Agent interactions on the UI too.

## Technical requirements
- Update the outdated design
  - Update to latest design system
  - Remove “browse dapps” tab
  - Remove “external contracts” for now, just do token balances and past transactions
- Requires: at least a basic version of the Radspec registry
  - Or at least the function name (e.g. how MetaMask does it)

# Design
- [Figma board](https://www.figma.com/file/cDLkOC1O54yVphU2wooX2CQ0/Onboarding-Voting-Agent-APP?node-id=14%3A128)
- [x] Kick off meeting to move into implementation (sprint 25, @dizzypaty)

# Implementation
- [x] Frontend
- [x] Information for transferred tokens in background script (@sohkai)
- [x] Finalize background script ([PR](https://github.com/aragon/aragon-apps/pull/952))
- [x] Test data with real Agent app
- [x] aragon.js Radspec handler (@sohkai)

**Comment by ghost** [comment]
# Design propose 
-Adapt to the new design system
-Remove all the external contracts

![Agent APP.png](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/cfe6f755-c455-4260-94b5-674699f4e00f)

# Responsive design
-Challenge: create a new responsive tables with a lot of fields on mobile 

![mobile_1.png](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/9af5f9ee-1fbe-42b6-b299-c3843ec76930)

![mobile2.png](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/95e06d50-e236-45cc-8aa9-60df410a9238)

![mobile 3.png](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/35f4f1e3-8958-4e84-b47c-39985e15fe7b)

**Comment by ghost** [comment]
**Check the FIGMA**
[FIGMA](https://www.figma.com/file/cDLkOC1O54yVphU2wooX2CQ0/Onboarding-Voting-Agent-APP?node-id=14%3A128)

**Comment by AquiGorka** [comment]
I will start with the html markup but implementing these designs require the new changes to visuals (new layout component, new button, etc)

**Comment by lkngtn** [comment]
@luisivan @izqui Should we create a seperate issue for the radspec registry?

**Comment by lkngtn** [comment]
Also question, is this being implemented as a seperate front-end app that is installed separately from the Agent app? (eg like finance is to vault)

Or if I install the agent app I will have this frontend included no matter what?

**Comment by izqui** [comment]
@lkngtn Yes, I would track the radspec registry separately.

I think this frontend should appear by default if an Agent instance is installed, otherwise another app would need to be installed in the organization.

**Comment by sohkai** [comment]
It is being implemented as the default UI for the Agent app, and will be shown alongside Finance if Finance uses the Agent as its Vault.

**Comment by lkngtn** [comment]
Okay thanks for the clarification. I suppose in the future we may be able to hide apps like this using the organization settings. My concern is that Finance (or other more specific interfaces for agent) may be preferred by an organization, and we wouldn't necessarily want to have this Agent ui included in then menu if there is another frontend being used.
