### ISSUE TITLE
Support meta-txs

### ISSUE THREAD

**Issue by facuspagnuolo** [aragonone/product#87]
# Idea
## User story
As as user, I want to be able to interact with an Aragon application without being require to have funds in my wallet.

## Technical requirements
To let the user seamlessly interact with Aragon without needing ETH, we need to implement meta-transaction support in aragonOS, implement at least 1 relayer, and the necessary changes to the signer panel.

## Implementation
- [x] Assess ecosystem status regarding meta-txs - [link](https://www.notion.so/aragon/Meta-Transactions-6a74d85f7c1d48f09d756b5a4e8908fa) (sprint 14)
- [x] MVP implementation of aragonOS contracts - [PR 526](https://github.com/aragon/aragonOS/pull/526) (sprint 14)
- [x] Review and discuss scope with Jorge (sprint 14)
- [x] Off-chain service implementation - [PR 527](https://github.com/aragon/aragonOS/pull/527) (sprint 14)
- [ ] Review full implementation (sprint 15)

**Comment by sohkai** [comment]
This is really important, but we are unlikely to be supporting this in mainline aragonOS versions at the moment. We will evaluate how to introduce this (and evaluate other meta-tx mechanisms, like the gas relayer network) in the future.
