### ISSUE TITLE
UX improvements for Voting

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#93]
# Idea
## User story
The current voting experience could be greatly enhanced by including UX wins from our Survey app.
There are some issues we have detected:

- The right panel is too small to display all proper information about a vote. Votes are important and should take the whole screen
- Users want stats of the votes over time

## Technical requirements
- Redesign app with survey UX
- Implement modifying suport and quorum
- Write human-friendly copies for support and quorum
- Allow to export votes in CSV
- Allow to see all votes casted / voting analytics

# Design
- [Figma board](https://www.figma.com/file/O09HJRCFDwDTni4VE3tiRvwI/Voting)
- [Prototype](https://www.dropbox.com/s/dchjupnybqqmhgm/COMPLETE_ARAGON_VOTING.mov?dl=0)

# Implementation
- [x] Work on the help modals
- [ ] Finalize implementation (@AquiGorka, @sohkai, Sprint 25/26)
- [x] Design review (@dizzypaty, Sprint 26)

**Comment by luisivan** [comment]
Sprint 14: Just kickoff meeting for the high-level scope, no design

**Comment by luisivan** [comment]
Kickoff meeting done, proceeding to design phase

**Comment by ghost** [comment]
First iteration done. Details about the re-design.

# Actual problem
-Identify quickly how is the status of the votes (in progress, finalized executed...)
-Identify the category of the vote (what type of vote is? finance? permission? governance?)
-Text out of context (avoid put information outside the container) more context in all the elements
-Scalability (structure, need more consistency)

![s1.png](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/a5522f48-854e-4698-ab75-8b6860a75a9a)

![s2.png](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/3236ef78-8ae8-4ab5-abc8-8b5203d69297)

# Card design 
-Define the category (be consistent and easy to identify with the icon+text)
-Reorder of the hierarchy of elements
-The new vote indicator (to know quickly if i already voted or not)
-And finally, the status (in progress, executed...)

![Voting-1.png](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/f13a9065-da44-4355-85e9-5b114faf0614)

![Voting.png](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/802ee55d-f211-4706-b457-d8c0bac9b45f)

# Design propose 
-Add the new design system
-Add filters
-Add the new cards

![preview.png](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/41837405-3cec-4225-bc46-0cc1667c37e1)

# New single vote page
-More space to describe all the vote
-New sidebar with interesting info about the progress of the voting
-We have the main actions with more visibility (not inside the signer panel)

![single page.png](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/dd9db6cf-821e-497f-bbb1-be0e671e7133)

# Single vote page (vote over/executed)
-The page changes focusing on the analysis

![VOTE-2.png](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/8f21597f-8997-4197-9ede-f8ecaed5a621)

![VOTE-3.png](https://images.zenhubusercontent.com/5c793b9c56c8d279d62b84e6/f9c5c816-fd3f-418e-98b4-b4fbba9fd59c)

**Comment by ghost** [comment]
**Check the video with the prototype** 
[Video voting](https://www.dropbox.com/s/dchjupnybqqmhgm/COMPLETE_ARAGON_VOTING.mov?dl=0)

**Check the FIGMA**
[FIGMA](https://www.figma.com/file/cDLkOC1O54yVphU2wooX2CQ0/Onboarding-Voting-Agent-APP?node-id=0%3A1)
